#ifndef MODEL_TIMINGS_H
#define MODEL_TIMINGS_H

#define ANIMATION_FPS 24.0f

/* Animation IDs */
#define ZOMBIE_WALK_ANIMATION 0
#define ZOMBIE_DEATH_ANIMATION 1
#define ZOMBIE_IS_DEAD_ANIMATION 2

#define ZOMBIE_WALK_ANIMATION_START 0
#define ZOMBIE_WALK_ANIMATION_END 15.0f / ANIMATION_FPS
#define ZOMBIE_DEATH_ANIMATION_START 20.0f / ANIMATION_FPS
#define ZOMBIE_DEATH_ANIMATION_END 41.0f / ANIMATION_FPS
#define ZOMBIE_IS_DEAD_ANIMATION_START 41.0f / ANIMATION_FPS
#define ZOMBIE_IS_DEAD_ANIMATION_END 42.0f / ANIMATION_FPS

#define ARMS_SLINGSHOT_FIRE_START 0
#define ARMS_SLINGSHOT_FIRE_END 27.0f / ANIMATION_FPS

#endif